//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 1:繁榮發達，信用得固，萬人仰望，可獲成功。(吉)
        ///2:動搖不安，一榮一枯，一盛一衰，勞而無功。(凶)
        ///3:立身出世，有貴人助，天賜吉祥，四海名揚。(吉)
        ///4:日被雲遮，苦難折磨，非有毅力，難望成功。(凶)
        ///5:陰陽和合，精神愉快，榮譽達利，一門興隆。(吉)
        ///6:萬寶集門，天降幸運，立志奮發，得成大功。(吉)
        ///7:精力旺盛，頭腦明敏，排除萬難，必獲成功。(吉)
        ///8:努力發達，貫徹志望，不忘進退，可期成功。(吉)
        ///9:雖抱奇才，有才無命，獨營無力，財利難望。(凶)
        ///10:烏雲遮月，暗淡無光，空費心力，徒勞無功。(凶)
        ///11:草木逢春，枝葉沾露，穩健著實，必得人望。(吉)
        ///12:薄弱無力，孤立無援，外祥內苦，謀事難成。(凶)
        ///13:天賦吉運，能得人望，善用智慧，必獲成功。(吉)
        ///14:忍得苦難，必有後福，是成是敗，稚靠興隆。(凶)
        ///15:謙恭做事，外得人和，大事成就，一門興隆。(吉)
        ///16:能獲眾望，成就大業，名利雙收，盟主四方。(吉)
        ///17:排陳萬難，有貴人助，把握時機，可得成功。(吉)
        ///18:經商做事，順利昌隆，如能慎始，百事亨通。(吉)
        ///19:成功雖早，慎防虧空，內外不和 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string _ref {
            get {
                return ResourceManager.GetString("_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;table width=&quot;560&quot; border=&quot;1&quot; cellspacing=&quot;1&quot; cellpadding=&quot;2&quot; align=&quot;center&quot; bordercolor=&quot;#CE5300&quot;&gt;
        ///                          &lt;tr bgcolor=&quot;#FFFFCC&quot;&gt;
        ///                            &lt;td colspan=&quot;8&quot; height=&quot;60&quot;&gt;
        ///                              &lt;p style=&quot;margin-top: 0; margin-bottom: 0&quot;&gt;&lt;font color=&quot;#990000&quot;&gt;&lt;span style=&quot;font-size: 12px&quot;&gt;&lt;font color=&quot;#FF0000&quot;&gt;&lt;strong&gt;『附錄字彙』&lt;/strong&gt;&lt;/font&gt;使用方法：&lt;/span&gt; &lt;/font&gt; &lt;/p&gt;
        ///                              &lt;p style=&quot;margin-top: 0; margin-bottom: 0&quot;&gt;&lt;font color=&quot;#990000&quot;&gt;&lt;spa [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string cc {
            get {
                return ResourceManager.GetString("cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1:
        ///一乙
        ///2:
        ///二人丁力乃又了几入卜刀
        ///3:
        ///三上千士土子小山川己已巳才久凡大于女及弓工干口丈丫丸夕下寸巾
        ///4:
        ///四仁仍升壬少心水中井介公火丰方木丹天太云允勻午友尹文日曰月化斗予牛之孔互亢冗戶爻牙止內王仃及屯今氏父支斤歹引元尤戈勿丑什切尺手犬夫比毛互仆分巴卞不反幻片
        ///5:
        ///五仕仙他仗仔仟代左付右令民冊世史巧功玄白田由甲申用目旦玉丘生主加占可兄石只叭弘台叮包卉叫另古尼召巨司句幼禾札本丙戊布卯未末必平市冬孕永立以央出北甘凹凸刊札母瓜正奴奶它外瓦充示卡去失斥丕乏半皮
        ///6:
        ///六光先圭戌艮羊地至向各吉名後舌合回同吒臣吋吊考多仲伉來企伊全伍仰任伙休价伏份在行汀州丞年存舟兆寺竹圳朱朴米朽打汁次冰交件列匠宅尖老宇守安字如妄亦聿因夷有衣羽而危耳印西先旭早百自旨曲收乒乓色此虫肉妃好帆亥充再共
        ///7:
        ///住佃但你伴佛佈伶夾利佣余位伸宋似作坐彷佘七妏妥妞努妝妘妤汝妙妨妣克告估君呂兌束局托豆足佔言佑佐吳吾呈杏串吹吟冶吸吵亨伯伺何含別刨吧灶杜町牡圾赤走成劫坍弄坊更男良均壯辰坎床杆杖李孚孝材村杉杞秀池汐汕汗廷江忍忘志刪形址見免車屁身甫貝旱步判私角改攻即弟系忙兵冷宏完我希序酉辛助彤夆
        ///8:
        ///八佶供佰侖佬彿岱佩夜欣 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string word {
            get {
                return ResourceManager.GetString("word", resourceCulture);
            }
        }
    }
}
